usre= str(input("enter tha name"))
password= int(input("enter tha password"))
if usre=="pihu":
    if password==4040:
        print("your account")
    else:
        print("worng password")
elif usre!="pihu":
    print("wrong name")
    if password!=4040:
            print("it is not your account")
            print("creat new account")
name=input("enter new name")
pas=input("enter new pasword")
print("its your new accunt")
        
            

     


